export default {
  // ACTIONS
  FACECARDS_RECEIVE_DATA: "FACECARDS_RECEIVE_DATA",
  FACECARDS_RECEIVE_DATA_ERROR: "FACECARDS_RECEIVE_DATA_ERROR",
  FACECARD_AWAIT_CREATION_RESPONSE: "FACECARD_AWAIT_CREATION_RESPONSE",
  FACECARD_RECEIVE_CREATION_RESPONSE: "FACECARD_RECEIVE_CREATION_RESPONSE",
  FACECARD_EDIT: "FACECARD_EDIT",
  FACECARD_EDIT_FINISH: "FACECARD_EDIT_FINISH",
  FACECARD_EDIT_SUBMIT: "FACECARD_EDIT_SUBMIT",
  FACECARD_TURN_NEXT: "FACECARD_TURN_NEXT",
  FACECARD_TURN_PREVIOUS: "FACECARD_TURN_PREVIOUS",
  FACECARD_SET_PAGENUMBER_TO_DEFAULT: "FACECARD_SET_PAGENUMBER_TO_DEFAULT",
  FACECARD_SHOW_RANDOM_CARD: "FACECARD_SHOW_RANDOM_CARD",

  // STATES
  FACECARD_EDITING: "FACECARD_EDITING",
  FACECARD_SUBMITTING: "FACECARD_SUBMITTING"
}
