export default {

    // actions
    SEARCH_START: "SEARCH_START",
    SEARCH_END: "SEARCH_END",
    SEARCH_SAVE_RESULTS: "SEARCH_SAVE_RESULTS",
    SEARCH_SET_TO_INITIAL: "SEARCH_SET_TO_INITIAL",

    // status
    SEARCH_NOT_SEARCHED: "SEARCH_NOT_SEARCHED",
    SEARCH_SEARCHING: "SEARCH_SEARCHING",
    SEARCH_FINISHED: "SEARCH_FINISHED"
}