export default {
    // ACTIONS
    USERSCORES_RECEIVE_DATA: "USERSCORES_RECEIVE_DATA",
    USERSCORE_AWAIT_RATING_RESPONSE: "USERSCORE_AWAIT_RATING_RESPONSE",
    USERSCORE_RECEIVE_RATING_RESPONSE: "USERSCORE_RECEIVE_RATING_RESPONSE",
    USERSCORE_EDIT_FINISH: "USERSCORE_EDIT_FINISH",
    USERSCORE_EDIT_SUBMIT: "USERSCORE_EDIT_SUBMIT",

    // STATUS
    USERSCORE_SUBMITTING: "USERSCORE_SUBMITTING"
}